# Generated by Django 2.2.7 on 2019-12-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20191228_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
