# Generated by Django 2.2.7 on 2019-12-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todoitem_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveditem',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
